FROM node:18-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN npm install -g pnpm && pnpm install --registry=https://mirrors.aliyun.com/pypi/simple/

COPY . .

EXPOSE 3001

CMD ["pnpm", "dev", "--host"]
